{
 "title": "ASP.NET Core Copy",
 "description": "ASP.NET Core metrics from OpenTelemetry",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(http_server_active_requests,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_server_active_requests{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_hosting_http_server_request_duration_sum",
     "legendFormat": "p50"
    },
    {
     "expr": "microsoft_aspnetcore_hosting_http_server_request_duration_sum",
     "legendFormat": "p75"
    },
    {
     "expr": "microsoft_aspnetcore_hosting_http_server_request_duration_sum",
     "legendFormat": "p90"
    },
    {
     "expr": "microsoft_aspnetcore_hosting_http_server_request_duration_sum",
     "legendFormat": "p95"
    },
    {
     "expr": "microsoft_aspnetcore_hosting_http_server_request_duration_sum",
     "legendFormat": "p98"
    },
    {
     "expr": "microsoft_aspnetcore_hosting_http_server_request_duration_sum",
     "legendFormat": "p99"
    },
    {
     "expr": "microsoft_aspnetcore_hosting_http_server_request_duration_sum",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "eshop_webapp_basketstate_basket_checkout_itemsrecord_bucket",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"4..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\", http_response_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Total Value of Baskets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "eshop_webapp_basketstate_basket_checkout_valuerecord_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Items at Basket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "eshop_webapp_basketstate_basket_checkout_itemsrecord_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Items in a Basket",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eshop_webapp_basketstate_basket_checkout_items)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Value in Baskets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eshop_webapp_basketstate_basket_checkout_valuerecord_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Connection Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(system_net_http_http_client_connection_duration_bucket)",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Total Unhandled Exceptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_runtime_dotnet_exceptions)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_hosting_http_server_request_duration_sum",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Top 10 Unhandled Exception Endpoints",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "eshop_webapp_basketstate_basket_checkout_itemsrecord_bucket",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_kestrel_active_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Open Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_net_http_http_client_open_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests HTTP Protocol",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(system_net_http_current_requests)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}