global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'basket-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5003'] # Adjust port to match your Basket.API service
  
  # Add other services as needed

  