global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'basket-api'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:7298'] 
  
  # Add other services as needed

  