apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    uid: PBFA97CFB590B2093
    isDefault: true
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://host.docker.internal:16686
    editable: true