{
 "title": "Basket Service Dashboard",
 "tags": [ "basket" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_seconds_count{job=\"basket-api\"}[1m])"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_seconds_sum{job=\"basket-api\"}[1m])/rate(http_server_duration_seconds_count{job=\"basket-api\"}[1m])"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_seconds_count{job=\"basket-api\",status_code=~\"5..\"}[1m]))/sum(rate(http_server_duration_seconds_count{job=\"basket-api\"}[1m]))*100"
    }
   ]
  }
 ]
}